


<nav  class="navbar navbar-static-top navbar-default">
  <div class="container">

    <div class="navbar-header">
           
 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
               <span class="fa fa-bars"></span>
      </button>
      <div class="navbar-brand">
     <a href="/" class=" btn btn-primary"><span class="fa fa-home"></span>&nbsp;BLLH.Org</a>
    </div>
    
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/welcome">New Here?</a></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ministries <span class="caret"></span></a>       
            <ul class="dropdown-menu">
              <li><a href="/youth">Youth</a></li>
              <li><a href="/adults">Adults</a></li>
              <li><a href="/music-and-arts">Music and Arts</a></li>
              <li><a href="/ways-to-help">Ways To Help</a></li>
            </ul>
          </li>

           <li><a href="http://www.mychurchevents.com/calendar/calendar.aspx?ci=L6K5J4N8G1F0O9N8H2" target="_blank">Events</a></li>
          <li><a href="/recent-sermons">Sermons</a></li>
          <li><a href="http://www.bllhschool.org/" target="_blank">Our School</a></li>
          <li><a href="https://www.eservicepayments.com/cgi-bin/Vanco_ver3.vps?appver3=Fi1giPL8kwX_Oe1AO50jRrbAUI4VUovCwliLaPmiKb8s4NSQukCYDzKLUtTTUlsf2EvVVAEjqawDomKT1pboubV6cdp_gVU6Enn7I3RUWgs=&ver=3" target="_blank">Give</a></li>

      </ul>
        <div class="navbar-form navbar-left hidden-sm">
        <$search/$> 
        </div>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /container-fluid -->
</nav>



