<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-md-4 ">
         <$element globalID="af09f7e3-ec25-4f83-af14-d0ba5f516f06"$><$/element$>
          
        </div>
        <div class="col-md-4 ">
         
            <$element globalID="31c94706-7540-4d11-b8a1-ba443509234d"$><$/element$>
        </div>
        <div class="col-md-4 ">
        <$element globalID="611fdf51-1efe-49dd-a069-e6694d2ff1ab"$><$/element$>
            
        </div>
        </div>
</div>